#+TITLE: Questions to Ask as a Software Engineering Interview Candidate
#+AUTHOR: Jonathan Jin

* Table Of Contents                                                        :TOC:
- [[#development][Development]]
  - [[#general][General]]
  - [[#technologies][Technologies]]
  - [[#qa][QA]]
  - [[#team-dynamic][Team Dynamic]]
- [[#hrqol][HR/QOL]]
- [[#credits][Credits]]
- [[#license][License]]

* Development
  
** General
   
   - On-call?
   - Team structure?
   - When was last crunch time?
   - What are some reasons why an engineer should join your company over the
     biggies, e.g. Google or FB?
   - What's your favorite part of the job?
   - What's something you have worked on or are currently working on that
     excites you?
   - Average number of hours *you* work? Any after-hours/weekends?
   - Typical required office hours? Are they flexible?
   - Communication/cooperation w/ international teams (if any); any late nights
     or early mornings as result?
   - How is inter-office/team mobility? Can engineers request transfers or
     choose to work from a given office temporarily; how easy is it to do so,
     and is this something that engineers tend to do? Is this something that is
     encouraged by the company?
   - What needs are your team currently attempting to fulfill with its current
     hiring efforts?
   - How autonomous/pressured do you feel in your work?
   - What kind of equipment and working environment are devs provided with? What
     is and is not expensable? Are devs free to customize, or are environments
     more standardized?
     
** Technologies
   
   - What's your stack?
   - What's your policy/practice regarding adoption of new technologies?
     
** QA
   
   - How does your team ensure/maintain product quality?
   - What's your build process like?

** Team Dynamic

   - How do you measure employee/engineer success?
   - How is success measured for a manager, team lead, etc.?
   - Has anybody left the team in the past year? If so, why?
   - What will I be expected to accomplish in the first N months?
   - How do you measure engineer growth, and how does growth factor into
     promotion and my responsibilities as an IC?
     
* HR/QOL
  
  - Vacation/PTO policy
  - WFH?
  - Bonus structure
  - Promotion schedule, if any
  - What proportion of your hires are experienced vs. new grads? What's the
    median and average years of experience that developers have?

* Credits

  A good deal of these questions came from [[https://www.reddit.com/r/cscareerquestions/comments/4ce2s3/resource_interview_questions_my_massive/][this post in r/cscareerquestions]].

* License
  
  #+BEGIN_VERBATIM
  This is free and unencumbered software released into the public domain.

  Anyone is free to copy, modify, publish, use, compile, sell, or
  distribute this software, either in source code form or as a compiled
  binary, for any purpose, commercial or non-commercial, and by any
  means.

  In jurisdictions that recognize copyright laws, the author or authors
  of this software dedicate any and all copyright interest in the
  software to the public domain. We make this dedication for the benefit
  of the public at large and to the detriment of our heirs and
  successors. We intend this dedication to be an overt act of
  relinquishment in perpetuity of all present and future rights to this
  software under copyright law.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
  IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
  OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
  OTHER DEALINGS IN THE SOFTWARE.

  For more information, please refer to <http://unlicense.org/>
  #+END_VERBATIM
