#+TITLE: Questions to Ask as a Software Engineering Interview Candidate
#+AUTHOR: Jonathan Jin

* Table Of Contents                                                        :TOC:
- [[#development][Development]]
  - [[#general][General]]
  - [[#technologies][Technologies]]
  - [[#qa][QA]]
  - [[#team-dynamic][Team Dynamic]]
- [[#hrqol][HR/QOL]]
- [[#diversity][Diversity]]
- [[#credits][Credits]]
- [[#license][License]]

* Development

** General

   - On-call?

   - Team structure?

   - When was last crunch time?

   - What sets your company/org/team apart from its peers in industry?

   - What's your favorite part of the job?
   - What's something you have worked on or are currently working on that
     excites you?
   - Average number of hours *you* work? Any after-hours/weekends?
   - Typical required office hours? Are they flexible?
   - Communication/cooperation w/ international teams (if any); any late nights
     or early mornings as result?
   - How is inter-office/team mobility? Can engineers request transfers or
     choose to work from a given office temporarily; how easy is it to do so,
     and is this something that engineers tend to do? Is this something that is
     encouraged by the company?
   - What needs are your team currently attempting to fulfill with its current
     hiring efforts?
   - How autonomous/pressured do you feel in your work?
   - What kind of equipment and working environment are devs provided with? What
     is and is not expensable? Are devs free to customize, or are environments
     more standardized?

** Technologies

   - What's your stack?
   - What's your policy/practice regarding adoption of new technologies?

** QA

   - How does your team ensure/maintain product quality?
   - What's your build process like?

** Team Dynamic

   - What will I be expected to accomplish in the first N months?
   - How does your team respond to outages -- both immediately, and afterwards?

     This question can help you to determine if a team "assigns blame" to individuals
     for outages, or takes a blameless, general post-mortem approach.

** Management

   These are questions both relating to management style -- both at the line/org
   level -- as well as more targeted questions intended to be asked to HMs.

   - How does the team approach planning? Are ICs consulted and given direct
     input into OKRs and priorities, or are they decided effectively "for them"
     by management?
   - How do you measure engineer growth, and how does growth factor into
     promotion and my responsibilities as an IC?
   - How do you measure employee/engineer success?
   - How is success measured for a manager, team lead, etc.?
   - Has anybody left the team in the past year? If so, why?
   - How does $company/$team do performance reviews?
     - Is peer review factored in?
     - Is review very simply between manager/report?
   - Who would you consider your company and org's most respected and
     influential leaders?  This can be independent of level, seniority, or even
     org.
     - What makes them so influential?
     - How does their work influence your management style?
   - Are there any engineering leaders -- either within or without the company
     -- that you respect? Why? How does their work influence yours?
   - How are new managers in $company/$org brought on? Say a new team is being
     formed, e.g. being spun off from a pre-existing, maybe more general team to
     focus on a more specific issue. How does $company/$org select a manager for
     this new team?
   - What sort of training is involved in somebody becoming a manager at
     $company/$org?
   - What do you consider the core pillars of a "good" manager? ("Good" here
     being intentionally vague)

* HR/QOL

  - Vacation/PTO policy
    - "How many days have you personally taken off in the past year?"
      - Good way to get a candid, objective response. If the HM tells it to you
        straight, then you have a good signal into a) exactly what "unlimited"
        really means and b) your HM's encouraged level of candor. And an HM
        being unwilling to discuss such details with you openly is also worth
        taking note of.
  - WFH?
  - Bonus structure
  - Promotion schedule, if any
  - What proportion of your hires are experienced vs. new grads? What's the
    median and average years of experience that developers have?

* Diversity

  - How diverse is your team, organization, etc.?
    - "If it's not diverse or less diverse than you'd like, why do you think
      that is?"
  - How diverse is engineering leadership? How engaged are they in the
    organization's DEI efforts?
  - What direct initiatives is your organization working on, if any, to
    prioritize or improve diversity?
  - What opportunities are there for me as an IC to contribute to improving
    diversity and inclusion within engineering at Company?

* Credits

  Some of these questions came from [[https://www.reddit.com/r/cscareerquestions/comments/4ce2s3/resource_interview_questions_my_massive/][this post in r/cscareerquestions]]. The
  majority of these grew out of my own iterative career experiences.

* License

  #+BEGIN_SRC text
    This is free and unencumbered software released into the public domain.

    Anyone is free to copy, modify, publish, use, compile, sell, or
    distribute this software, either in source code form or as a compiled
    binary, for any purpose, commercial or non-commercial, and by any
    means.

    In jurisdictions that recognize copyright laws, the author or authors
    of this software dedicate any and all copyright interest in the
    software to the public domain. We make this dedication for the benefit
    of the public at large and to the detriment of our heirs and
    successors. We intend this dedication to be an overt act of
    relinquishment in perpetuity of all present and future rights to this
    software under copyright law.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
    IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.

    For more information, please refer to <http://unlicense.org/>
  #+END_SRC
